### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by maxengel** [rbribeiro/wingpanel-indicator-dropbox#10]
When trying to build from source I receive the following:
```
Dependency wingpanel-2.0 found: NO (tried cmake)

meson.build:23:0: ERROR:  Could not generate cargs for wingpanel-2.0:
```

**Comment by rbribeiro** [comment]
Strange... Do you have wingpanel installed? What version of eOS are you using?

**Comment by maxengel** [comment]
I am running Wingpanel 2.3.2 and eOS 5.1.7

**Comment by IzsakiRobi** [comment]
Try apt install libwingoanel2-dev…
I use elemntary 6 preview if i install libvingpanel-2 and libwingoanel2-dev from hera deb, compiled and running fine 😊

rob
________________________________
Feladó: Max Engel ***@***.***>
Elküldve: Sunday, April 18, 2021 5:08:24 AM
Címzett: rbribeiro/wingpanel-indicator-dropbox ***@***.***>
Másolatot kap: Subscribed ***@***.***>
Tárgy: Re: [rbribeiro/wingpanel-indicator-dropbox] Unable to build from source (#10)


I am running Wingpanel 2.3.2 and eOS 5.1.7

**Comment by maxengel** [comment]
The .deb version installs fine; it is just when compiling from source. Are there package dependencies for it to compile correctly?

**Comment by rbribeiro** [comment]
Have you tried @IzsakiRobi suggestions? There are some typos in his answer in case you have just copied it. Try installing libwingpanel-2.0-0  and libwingpanel-2.0-dev

To be more precise, the dependencies needed are: _wingpanel-2.0, gtk+-3.0, granite, json-glib-1.0_

**Comment by maxengel** [comment]
@rbribeiro Thanks for the additional info. Unfortunately that didn't work. After doing some troubleshooting, I think the issue is around the dependencies.

I ran: `sudo apt install libgranite-dev gtk+-3.0 libjson-glib-dev` and was able to get it past `meson build --prefix=/usr`.

After that, it built successfully from source.

**Comment by rbribeiro** [comment]
Great! I hope the indicator can be useful!

**Comment by maxengel** [comment]
It might be worth updating the documentation to include those dependencies in the `Compile from source` section of the readme.

**Comment by maxengel** [comment]
@rbribeiro FYI, I installed this on the Odin nightly and was unable to build from source since the `libwingpanel-2.0-dev` and `gtk+-3.0` packages are not available in the repo.
