### ISSUE TITLE
Flatpak/Flathub support

### ISSUE THREAD

**Issue by andirsun** [rbribeiro/wingpanel-indicator-dropbox#2]
Hi!, do you have any plans to upload your project to flathub as flatpak ?
It can be useful to download in the appcenter.

**Comment by rbribeiro** [comment]
Hey! Do be honest, I did think about that. I totally forgot that making it available through Flathub would be a shortcut to make it available in the AppCenter. I will see what I can do! Thanks for your suggestion.

**Comment by rbribeiro** [comment]
> Hi!, do you have any plans to upload your project to flathub as flatpak ?
> It can be useful to download in the appcenter.

I checked the possibility of upload to flathub. Unfortunately, it is not possible. Wingpanel check for indicators in a specific directory where flatplaks don't have access to install files.
