### ISSUE TITLE
Activate on single click

### ISSUE THREAD

**Issue by pongloongyeat** [rbribeiro/wingpanel-indicator-dropbox#6]
Elementary uses activate on single click for stuff in ListBoxes afaik (see the Network Indicator). You may want to change this to true.

https://github.com/rbribeiro/wingpanel-indicator-dropbox/blob/22e124c5e74dc9bcd24f60ed538a43164590c109/src/Widgets/FileEntryList.vala#L32

**Comment by rbribeiro** [comment]
But if I click on a file path link, does this trigger the activate signal ?

**Comment by rbribeiro** [comment]
Changed the behaviour... I'm closing this. Thanks!
