### ISSUE TITLE
Display icon seems a little big

### ISSUE THREAD

**Issue by pongloongyeat** [rbribeiro/wingpanel-indicator-dropbox#8]
As title implies. Not sure what size elementaryOS uses (I'm guessing it's 16x16) but the Dropbox indicator icon is noticeably bigger.

![image](https://user-images.githubusercontent.com/31680656/105223814-3efeb000-5b97-11eb-8745-8289b03e248a.png)

**Comment by rbribeiro** [comment]
Sorry for the late response. I think you right, it seems bigger than the other indicators. I will check that!
