### ISSUE TITLE
Installation after using Dropbox .deb

### ISSUE THREAD

**Issue by maxengel** [rbribeiro/wingpanel-indicator-dropbox#9]
I installed Dropbox on eOS by using the official .deb. Is the CLI .py script still necessary for this to work, or is the Dropbox CLI installed as part of the Dropbox package installation?

**Comment by rbribeiro** [comment]
The package will install only the indicator. You must have the Dropbox CLI installed... If you can, I suggest you compile the indicator from source, since it has the most updated version.

**Comment by maxengel** [comment]
Got it, thanks!

I guess my question was actually more: do you know if Dropbox installs the CLI with their .deb? I realize this might be a question for Dropbox ;-)

**Comment by rbribeiro** [comment]
Yes, it does! ;)

**Comment by maxengel** [comment]
@rbribeiro thanks so much! Have you thought about listing this in the eOS App Center? I'd love to pay you for it to support further development.

**Comment by rbribeiro** [comment]
@maxengel, unfortunately the eOS AppCenter doesn't accept wingpanel indicators. If there is any change in their policy in the future, I definitely would submit it to the AppCenter, it is the easiest way to distribute an app.

**Comment by maxengel** [comment]
got it. if you launch a GitHub sponsorship, I'd also do that!
